### ISSUE TITLE
Question...

### ISSUE THREAD

**Issue by Myzhar** [mike5ch/STM32L053-PWM-DMA-driving-WS2812#1]
Hi @mike5ch,

have you succeded in this project?

I'm working on it and I found your code... but I cannot make it work.

Thank you
Walter

**Comment by mike5ch** [comment]
What happens? With my 24 LED ring it worked fine.

**Comment by Myzhar** [comment]
Hi @mike5ch,
It's been a month since I opened this issue and I faced how to solve the problem.
I ported the code on a STm32F4 and now it works very well.
If I remember well my problem was with one of the registers of the PWM that is 32bit instead of 16bit and I made a little correction to the timing for low and high bit levels.

If you are curious about it you can find my code here:
https://github.com/RoboSec/rs_sensor_board/blob/devel/FW-rs_sensor_board/Src/ws2812_handler.c

Thank you very much for your code, it was really helpful
Walter
